export const timelineItems = [
  {
    id: 1,
    role: "Full-Stack Development Assistant",
    company: "InPower Br",
    period: "Jan 2026 — Present",
    startYear: "2026",
    desc: "Developing marketplace integration solutions, building front-end and back-end features, microservices, REST APIs, and coordinating project workflows through Kanban, daily stand-ups, and weekly planning.",
    color: "#a78bfa",
    tags: [
      "Java",
      "Spring Boot",
      "Go",
      "Gin",
      "React",
      "TypeScript",
      "Microservices",
      "PostgreSQL",
      "SAP HANA",
      "SAP",
    ],
  },
  {
    id: 2,
    role: "Full-Stack Development Intern",
    company: "InPower Br",
    period: "Oct 2025 — Jan 2026",
    startYear: "2025",
    desc: "Worked on ERP integrations between SAP and Bling, developing front-end features, REST APIs, and back-end services with modern web technologies.",
    color: "#2aa6f2",
    tags: [
      "Java",
      "Spring Boot",
      "Go",
      "Gin",
      "PostgreSQL",
      "Hibernate",
      "React",
      "TypeScript",
      "SAP HANA",
      "SAP",
    ],
  },
];
