name: CI Pipeline

on:
  push:
    branches:
      - master
      - dev

jobs:
  check-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "npm"

      - name: Install Dependecies
        run: npm ci

      - name: Run EsLint
        run: npm run lint

      - name: Run Build Test
        run: npm run build
